### ISSUE TITLE
Broken image in lectures/intro/conversions

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#20]
https://github.com/princomp/princomp.github.io/blob/0d923a06743e326758087d757aa12bcd0898987f/source/lectures/intro/conversions.md?plain=1#L131

**Comment by aubertc** [comment]
https://github.com/princomp/princomp.github.io/commit/ddd2cd04c4b8b16ed777cfc5436c267a2f7c7451 will solve that.
