### ISSUE TITLE
Broken formatting in labs/ClassDiagram

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#26]
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/labs/ClassDiagram.md?plain=1#L87-L89

Dropdown seems to be interfering with any markdown formatting on the text, as both inline code and the link seem to be broken.

https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/labs/ClassDiagram.md?plain=1#L97

Potential typo at end of line.

**Comment by aubertc** [comment]
https://github.com/princomp/princomp.github.io/commit/8316ae87becad324a5e743d98c363089f044d01d took care of the typo, I'm investigating the first element.

**Comment by aubertc** [comment]
Ok, I'm clueless on this one. I'll have to do some more testing, but I really don't know where it's coming from.

**Comment by aubertc** [comment]
![Screenshot_20240625_104601](https://github.com/princomp/princomp.github.io/assets/16466689/5e5668c5-ccf4-4049-88d3-18ebeca528b6)

This issue has not been resolved.

**Comment by jweeks2023** [comment]
Sorry, thought I fixed that one. It is now fixed with 0ee4850.

![image](https://github.com/princomp/princomp.github.io/assets/88799372/a9689225-ec71-49ba-a84a-6d701938ced5)

**Comment by aubertc** [comment]
Wow. Thanks. I never got to completely understand how to write markdown inside `section`, so yes documenting this could be helpful.
