### ISSUE TITLE
Broken table in labs/GradeCalculator

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#27]
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/labs/GradeCalculator.md?plain=1#L22-L27

Update to quartz-supported format

**Comment by aubertc** [comment]
https://github.com/princomp/princomp.github.io/commit/0821c0a62340edaaee49ebc14e817f2dd9ea5948 fixes this.
