### ISSUE TITLE
Weird header formatting on labs/While

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#31]
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/labs/While.md?plain=1#L67

On the website, the header seems to take up an extra line for seemingly no reason.

**Comment by aubertc** [comment]
Not the best indeed, but it's to accommodate the anchor symbol that appears when the title is hovered. 
![image](https://github.com/princomp/princomp.github.io/assets/16466689/a88fbb5c-0ca6-49f0-8bab-395f36833762)

In short: that's by design.
