### ISSUE TITLE
Reconsider tags from Academic Life pages

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#32]
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/docs/academic_life/ca.md?plain=1#L1-L7
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/docs/academic_life/choosing_major.md?plain=1#L1-L6
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/docs/academic_life/getting_help.md?plain=1#L1-L7
https://github.com/princomp/princomp.github.io/blob/c3c4fb718277f70da37d2a693f2533b70bd51637/source/docs/academic_life/uca_guide.md?plain=1#L1-L7

Since these no longer fit with the current tags we've chosen, it may be worth editing/removing these tags.

**Comment by aubertc** [comment]
Please, proceed as you see fit. The ` Augusta University` tag is probably useful to make the difference between information targeted to AU student and general PCP themes (useful to other students as well).

**Comment by jweeks2023** [comment]
I think an `Augusta-University` tag would be fine given your reasoning. I'll go ahead and remove the other tags and add this one to our current tags file.

**Comment by aubertc** [comment]
Thanks for taking care of it.

**Comment by aubertc** [comment]
Please, add the tag to source/tags.

**Comment by aubertc** [comment]
Closed with https://github.com/princomp/princomp.github.io/commit/e8165363a515202f98a949e5514fbfd2b6d15228
