### ISSUE TITLE
Tables render incorrectly

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#7]
Markdown tables are currently rendering incorrectly. They render as their plaintext form instead of the proper table format.

See https://github.com/princomp/princomp.github.io/blob/main/source/docs/programming_and_computer_usage/datatypes_in_csharp.md for example

**Comment by jweeks2023** [comment]
Potential solution: https://quartz.jzhao.xyz/plugins/GitHubFlavoredMarkdown

**Comment by aubertc** [comment]
https://github.com/princomp/princomp.github.io/commit/a664f81186e85c28bd414564ec6330b9837b5e41 , https://github.com/princomp/princomp.github.io/commit/fa738704aea94523c808d7e2ee9b73ad9bf748dd and https://github.com/princomp/princomp.github.io/commit/85ca04789cc2b09caa2b63e15ad6daa527da2af5 sorted this out. 

Feel free to re-open this issue if you see any table improperly typeset.
